global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'micrometer-example'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.67.1:9191' ]
        labels:
          application: 'Micrometer Application'